//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSUIR.TermWork.ImageViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSUIR.TermWork.ImageViewer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Account_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are different!.
        /// </summary>
        public static string Account_DifferentPassowrds {
            get {
                return ResourceManager.GetString("Account_DifferentPassowrds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Account_Edit {
            get {
                return ResourceManager.GetString("Account_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Account_FirstName {
            get {
                return ResourceManager.GetString("Account_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Account_LastName {
            get {
                return ResourceManager.GetString("Account_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Account_Register {
            get {
                return ResourceManager.GetString("Account_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Account_SignIn {
            get {
                return ResourceManager.GetString("Account_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Account_SignOut {
            get {
                return ResourceManager.GetString("Account_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Account_Unknown {
            get {
                return ResourceManager.GetString("Account_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Account_User {
            get {
                return ResourceManager.GetString("Account_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Name.
        /// </summary>
        public static string AlbumName {
            get {
                return ResourceManager.GetString("AlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such email already exists!.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is too long!.
        /// </summary>
        public static string EmailTooLong {
            get {
                return ResourceManager.GetString("EmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty!.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album name is too long!.
        /// </summary>
        public static string Exception_AlbumNameTooLong {
            get {
                return ResourceManager.GetString("Exception_AlbumNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is too long!.
        /// </summary>
        public static string Exception_CommentTooLong {
            get {
                return ResourceManager.GetString("Exception_CommentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is too large!.
        /// </summary>
        public static string Exception_ContentTooLarge {
            get {
                return ResourceManager.GetString("Exception_ContentTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type is too long!.
        /// </summary>
        public static string Exception_ContentTypeTooLong {
            get {
                return ResourceManager.GetString("Exception_ContentTypeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is too long.
        /// </summary>
        public static string Exception_DescriptionTooLong {
            get {
                return ResourceManager.GetString("Exception_DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album with such name already exists!.
        /// </summary>
        public static string Exception_DuplicateAlbumName {
            get {
                return ResourceManager.GetString("Exception_DuplicateAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album name is empty!.
        /// </summary>
        public static string Exception_EmptyAlbumName {
            get {
                return ResourceManager.GetString("Exception_EmptyAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is empty!.
        /// </summary>
        public static string Exception_EmptyComment {
            get {
                return ResourceManager.GetString("Exception_EmptyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content is empty!.
        /// </summary>
        public static string Exception_EmptyContent {
            get {
                return ResourceManager.GetString("Exception_EmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content type is empty!.
        /// </summary>
        public static string Exception_EmptyContentType {
            get {
                return ResourceManager.GetString("Exception_EmptyContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is empty!.
        /// </summary>
        public static string Exception_EmptyDescription {
            get {
                return ResourceManager.GetString("Exception_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is empty!.
        /// </summary>
        public static string Exception_EmptyExtension {
            get {
                return ResourceManager.GetString("Exception_EmptyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image name is empty!.
        /// </summary>
        public static string Exception_EmptyImageName {
            get {
                return ResourceManager.GetString("Exception_EmptyImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag is empty!.
        /// </summary>
        public static string Exception_EmptyTag {
            get {
                return ResourceManager.GetString("Exception_EmptyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension is too long!.
        /// </summary>
        public static string Exception_ExtensionTooLong {
            get {
                return ResourceManager.GetString("Exception_ExtensionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is too large!.
        /// </summary>
        public static string Exception_FileTooLarge {
            get {
                return ResourceManager.GetString("Exception_FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image name is too long!.
        /// </summary>
        public static string Exception_ImageNameTooLong {
            get {
                return ResourceManager.GetString("Exception_ImageNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is incorrect!.
        /// </summary>
        public static string Exception_InvalidDate {
            get {
                return ResourceManager.GetString("Exception_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The album is null!.
        /// </summary>
        public static string Exception_NullAlbum {
            get {
                return ResourceManager.GetString("Exception_NullAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image is null!.
        /// </summary>
        public static string Exception_NullImage {
            get {
                return ResourceManager.GetString("Exception_NullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner is null!.
        /// </summary>
        public static string Exception_NullOwner {
            get {
                return ResourceManager.GetString("Exception_NullOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tags is null!.
        /// </summary>
        public static string Exception_NullTags {
            get {
                return ResourceManager.GetString("Exception_NullTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag is too long!.
        /// </summary>
        public static string Exception_TagTooLong {
            get {
                return ResourceManager.GetString("Exception_TagTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name field is missing!.
        /// </summary>
        public static string FirstNameMissing {
            get {
                return ResourceManager.GetString("FirstNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid!.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long!.
        /// </summary>
        public static string InvalidFirstNameLength {
            get {
                return ResourceManager.GetString("InvalidFirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long!.
        /// </summary>
        public static string InvalidLastNameLength {
            get {
                return ResourceManager.GetString("InvalidLastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length is incorrect!.
        /// </summary>
        public static string InvalidPasswordLength {
            get {
                return ResourceManager.GetString("InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password!.
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name field is missing!.
        /// </summary>
        public static string LastNameMissing {
            get {
                return ResourceManager.GetString("LastNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has been completed successfully..
        /// </summary>
        public static string Operation_Success {
            get {
                return ResourceManager.GetString("Operation_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed! Try again!.
        /// </summary>
        public static string OperationFailure {
            get {
                return ResourceManager.GetString("OperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation field is empty!.
        /// </summary>
        public static string PasswordConfirmationMissing {
            get {
                return ResourceManager.GetString("PasswordConfirmationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is missing!.
        /// </summary>
        public static string PasswordMissing {
            get {
                return ResourceManager.GetString("PasswordMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RemeberMe {
            get {
                return ResourceManager.GetString("RemeberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
    }
}
